POST http://localhost:8080/user
Content-Type: application/json

{
 "id": "0",
 "userName": "Jack",
 "email": "jack@mail.com"
}

###
GET http://localhost:8080/user/1
Accept: application/json

### Basic auth
GET http://localhost:8080/user
Authorization: Basic Harry 1234
Accept: application/json

### Basic auth (fails)
GET http://localhost:8080/user
Authorization: Basic Not_Harry 1234
Accept: application/json


### Basic auth
GET http://localhost:8080/user
Authorization: Basic Harry 12345
Accept: application/json
